version: 0.2

phases:
  install:
    commands:
      - echo Installing Bun...
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - echo Installing dependencies with Bun...
      - bun install

  build:
    commands:
      - echo Building the React app with Bun...
      - bun run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no
